# Generated by Django 2.0.1 on 2022-03-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220322_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
