# Generated by Django 2.0.1 on 2022-03-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220322_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
